export const BAQ = [
    `What is the role of a business analyst in an organization?`,
    `As a Business Analyst what is your role in an organization?`,
    `What, according to you, are the core competencies of a Business Analyst?`,
    `List some of the skills and tools used by Business Analysts.`,
    `What are the different tools used in Business Analytics?`,
    `What is Menzies as a company?`,
    `What are the goals of the company?`,
    `What are Menzies goals?`,
    `What are the core values of the company?`,
    `What are the essential tools for business analysts?`,
    `Can you name the tools that are helpful for business analysis?`,
    `Why do you want to work as a business analyst at our organisation?`,
    `why do you want to work here?`,
    `What qualities do you have that make you a good business analyst?`,
    `How do you see yourself fit for the role of business analyst in our company?`,
    `What change would you bring to this organisation?`,
    `What makes you unique from others?`,
    `why should we hire you?`,
    `Do you have any technical skills? Can you list your database skills or business intelligence skills?`,
    `What do you mean by project deliverables?`,
    `What does INVEST mean?`,
    `What is INVEST?`,
    `Define analytical reporting.`,
    `What do you consider the most crucial part of analytical reporting?`,
    `If there are multiple stakeholders in a project, how do you influence them? `,
    `How would you handle a difficult or challenging stakeholder or client?`,
    `How can you handle and manage the difficult stakeholders?`,
    `How do you persuade a client to follow your business advice?`,
    `Have you ever disagreed with a colleague when completing a project?`,
    `How do you explain technical concepts to clients?`,
    `What do you consider the most challenging part of working as a business analyst?`,
    `How do you handle several tasks at once?`,
    `What is the difference between functional and non-functional requirements?`,
    `During the development of a system, how do you manage frequently changing customers' requirements?`,
    `How will you be able to handle the changes to requirements?`,
    `When can a business analyst say that the requirements are done?`,
    `How can you say that a requirement is good or perfect?`,
    `Do you think a business analyst should be involved in testing?`,
    `What is meant by Benchmarking?`,
    `What is Benchmarking?`,
    `What is agile methodology?`,
    `What is the Agile Manifesto?`,
    `What are the different types of Agile methodologies?`,
    `What are the essential qualities of an Agile business analyst?`,
    `What is the difference between extreme programming and scrum?`,
    `When should you use the Waterfall model instead of Scrum?`,
    `What are business risks?`,
    `Differentiate between a Risk and an Issue?`,
    `Tell me about yourself`,
    `what is your greatest strength and weakness?`,
    `what would your co-workers say about you?`,
    `what are your salary expectations?`,
    `what do you like to do outside of work?`,
    `where do you see yourself in 5 years?`,
    `describe your leadership style`,
    `do you have any questions for me?`
  ];