export const CC = [
  { que: `what chart would you use to visualize ...`, ans: null },
  { que: `design a pie chart from a normal excel table`, ans: null },
  { que: `design a pie chart from a pivot table`, ans: null },
  { que: `design a treemap from a normal excel table`, ans: null },
  { que: `design a bar chart from a normal excel table`, ans: null },
  { que: `design a bar chart from a pivot table`, ans: null },
  { que: `design a stacked bar chart from a normal excel table`, ans: null },
  { que: `design a stacked bar chart from a pivot table`, ans: null },
  { que: `design a waterfall chart from a normal excel table`, ans: null },
  { que: `design a funnel chart from a normal excel table`, ans: null },
  { que: `design a histogram from a normal excel table`, ans: null },
  { que: `design a line chart from a normal excel table`, ans: null },
  { que: `design a line chart from a pivot table`, ans: null },
  { que: `design a combo chart from a normal excel table`, ans: null },
  { que: `design a combo chart from a pivot table`, ans: null },
  { que: `design a ribbon chart from a normal excel table`, ans: null },
  { que: `design an area chart from a normal excel table`, ans: null },
  { que: `design an area chart from a pivot table`, ans: null },
  { que: `design a boxplot from a normal excel table`, ans: null },
  { que: `design a scatterplot from a normal excel table`, ans: null },
  { que: `design a spark line chart from a normal excel table`, ans: null },
];
