export const EF = [
  { que: `remove white spaces from data`, ans: `TRIM` },
  { que: `capitalize the first letter of every word`, ans: `PROPER` },
  { que: `capitalize every letter`, ans: `UPPER` },
  { que: `convert every letter to small letters`, ans: `LOWER` },
  { que: `display the number of characters in cell incl. space`, ans: `LEN` },
  { que: `extract the first n characters of a cell value`, ans: `LEFT` },
  { que: `extract the last n characters of a cell value`, ans: `RIGHT` },
  { que: `extract the n characters inside a cell content`, ans: `MID` },
  { que: `join multiple cell values`, ans: `CONCATENATE or &` },
  {
    que: `display the position number of a case-sensitive character in a cell`,
    ans: `FIND`,
  },
  {
    que: `display the position number of a case-insensitive character in a cell`,
    ans: `SEARCH`,
  },
  { que: `add prefix to cell`, ans: null },
  { que: `add suffix to cell`, ans: null },
  { que: `replace a number of characters in a cell`, ans: `REPLACE` },
  {
    que: `replace a portion of existing text or character in a cell`,
    ans: `SUBSTITUTE`,
  },
  {
    que: `how many cells contain only numbers`,
    ans: `COUNT: used to count number of cells in a range that contain numbers ie. (date numbers, integers, double)`,
  },
  { que: `what is the number of non-empty cells`, ans: `COUNTA` },
  { que: `what is the number of empty cells?`, ans: `COUNTBLANK` },
  { que: `how many cells contain a particular text`, ans: `COUNTIF` },
  { que: `do cell A and B contain the same values?`, ans: `=` },
  { que: `do cell A and B contain different values?`, ans: `<>` },
  { que: `is cell A greater than B?`, ans: `>` },
  { que: `is cell A less than B?`, ans: `<` },
  { que: `is cell A greater than or equal to B?`, ans: `>=` },
  { que: `is cell A less than or equal to B?`, ans: `<=` },
  {
    que: `display a result based on the condition that cell A and B hold true`,
    ans: `AND`,
  },
  { que: `find the modulo of a number`, ans: `MOD` },
  { que: `give an example of IF function`, ans: `IF` },
  { que: `give an example of nested IF function`, ans: `IF` },
  { que: `generate a list of dates within a given period`, ans: null },
  { que: `display today's date`, ans: `TODAY or Ctrl+;` },
  { que: `display the date in the next n days`, ans: `TODAY()+n` },
  { que: `display the date in the previous n days`, ans: `TODAY()-n` },
  { que: `display the opposite of TRUE or FALSE outputs`, ans: `NOT` },
  {
    que: `catch an error that could be thrown by a condition not met`,
    ans: `IFERROR`,
  },
  {
    que: `calculate the sum of values in a range A which meet a certain condition in that same range A`,
    ans: `SUMIF with 2 args`,
  },
  {
    que: `calculate the sum of values in a range A which meet a certain condition in another range B`,
    ans: `SUMIF with 3 args`,
  },
  {
    que: `calculate the sum of values in a range A which meet a certain condition in multiple ranges B, C, D, etc.`,
    ans: `SUMIFS`,
  },
  {
    que: `find the sum of values in range/column A where range/column A satisfies a condition`,
    ans: `SUMIF with 2 args`,
  },
  {
    que: `find the sum of values in range/column A where range/column B satisfies a condition`,
    ans: `SUMIF with 3 args`,
  },
  {
    que: `find the sum of values in range/column A where range/column B, C and D etc. satisifies a condition`,
    ans: `SUMIFS`,
  },
  { que: `find the total x in column Z where x=abc`, ans: `SUMIF with 2 args` },
  {
    que: `find the total x in column Z where column A=abc`,
    ans: `SUMIF with 3 args`,
  },
  {
    que: `find the total x in column Z where column A=abc and column B=def`,
    ans: `SUMIFS`,
  },
  {
    que: `how many cells in range A meet a certain condition in that range A`,
    ans: `COUNTIF`,
  },
  {
    que: `find the total number of x in column Z where column A=abc and column B=def`,
    ans: `COUNTIFS`,
  },
  {
    que: `find the number of x in column Z where x=abc`,
    ans: `COUNTIF`,
  },
  {
    que: `calculate the average of values in a range A which meet a certain condition in that same range A`,
    ans: `AVERGEIF with 2 args`,
  },
  {
    que: `calculate the average of values in a range A which meet a certain condition in another range B`,
    ans: `AVERGEIF with 3 args`,
  },
  {
    que: `calculate the average value in a range A which meet a certain condition in multiple ranges B, C, D, etc.`,
    ans: `AVERAGEIFS`,
  },
  {
    que: `find the average value in range/column A where range/column A satisfies a condition`,
    ans: `AVERAGEIF with 2 args`,
  },
  {
    que: `find the average value in range/column A where range/column B satisfies a condition`,
    ans: `AVERAGEIF with 3 args`,
  },
  {
    que: `find the average value in range/column A where range/column B, C and D etc. satisifies a condition`,
    ans: `AVERAGEIFS`,
  },
  {
    que: `find the average x in column Z where x=abc`,
    ans: `AVERAGEIF with 2 args`,
  },
  {
    que: `find the average x in column Z where column A=abc`,
    ans: `AVERAGEIF with 3 args`,
  },
  {
    que: `find the average x in column Z where column A=abc and column B=def`,
    ans: `AVERAGEIFS`,
  },
  { que: ``, ans: `` },
  { que: ``, ans: `` },
  { que: ``, ans: `` },
  { que: ``, ans: `` },
  { que: ``, ans: `` },
  { que: ``, ans: `` },
  { que: ``, ans: `` },
  { que: ``, ans: `` },
  { que: ``, ans: `` },
  { que: ``, ans: `` },
];
