import { BAQ } from "./Business Analyst";
import { PQ } from "./Power Query";
import { EI } from "./Excel Interview";
import { EF } from "./Excel formulas and common practices";
import { CC } from "./ExcelChooseDesignCharts";
import { SQLP } from "./SQL Practice";
import { DA } from "./Data Analyst interview";
import { GI } from "./General interview incl Company questions";
import { SQLI } from "./SQL Interview";
export { BAQ, PQ, EI, EF, CC, SQLP, DA, GI, SQLI };
