import { BAQ } from "./Business Analyst";
import { PQ } from "./Power Query";
import { EI } from "./Excel Interview";
import { EF } from "./Excel formulas and common practices";
import { CC } from "./ExcelChooseDesignCharts";
import { SQLP } from "./SQL Practice";
import { DA } from "./Data Analyst interview";
import { GI } from "./General interview incl Company questions";
import { SQLI } from "./SQL Interview";
import { OP } from "./Outlook common practices";
import { NP } from "./NATO Phonetic Alphabet";
import { PBI } from "./PowerBI Charts Practice";
import { VBA } from "./Excel VBA Macros";
import { PDX } from "./PowerBI Dax Practice";
export { BAQ, PQ, EI, EF, CC, SQLP, DA, GI, SQLI, OP, NP, PBI, VBA, PDX };
