export const PQ = [
  `merge data in multiple columns`,
  `split column data into multiple columns`,
  `trim data`,
  `convert data to upper, lower, proper case`,
  `add suffix and prefix to column data`,
  `extract the left, right and mid of column data`,
  `extract text with delimeter`,
  `extract year, quarter, month, day from a date`,
  `extract the earliest and latest dates`,
  `find the difference between dates`,
  `extract name of day and name of month`,
  `extract the day of the week or month`,
  `extract the week of the month or week of the year`,
  `extract the date from a datetime`,
  `calculate age from a date`,
  `add, subtract, divide and multiply column data`,
  `calc the percentage, percentage of and modulo of column data`,
  `calc the round off of column data`,
  `check if column data contains even or odd numbers`,
  `count number of duplicates in a column`,
  `count number of unique values in a column`,
  `filter out the rows of the column who has duplicate values`,
  `check the sign of numbers in column data`,
  `append multiple excel tables with different number of colums`,
  `append multiple excel tables/sheets from a single workbook`,
  `append multiple excel files from a folder`,
  `append multiple csv files from a folder`,
  `append different data source files`,
  `merge tables from the same sheets`,
  `merge sheets tables from the same workbook`,
  `merge data having multiple matching columns or criteria`,
  `merge data from multiple excel files/workbooks`,
  `merge data from different data sources`,
  `use column from examples to extract portion of a column data`,
  `use column from examples to create a new column from multiple column data`,
  `use column from examples to create a new month/day/year column from a date column`,
  `use column from examples to create a new column from an alphanumeric complex column data`,
  `create a new column which contains data based on the conditions of a single column data`,
  `create a new column which contains data based on the conditions of multiple column data. (eg. generating title for people based on Gender and MarriageStatus)`,
  `create a new column which contains data based on comparing 2 columns`,
  `create a new column to produce new info based on if date is before, equal or after a certain date`,
  `fill down empty values using default value given`,
  `create multiple groupings of a column(s) into one table (eg. for each branch, group the total income, average rating and minimum unit payment)`,
  `transpose a table (ie. reverse the columns and rows of that table)`,
  `unpivot a table`,
  `remove all rows whose column values are an error`,
  `replace all errors in a column`,
  `replace only one column value with new value`,
  `replace matching values in a column with a new value`,
  `choose only the columns you want to keep`,
  `what are the total number of rows in the dataset`,
  `go to a specific column without scrolling`,
];
