export const NP = [
  { que: `A`, ans: `Alpha` },
  { que: `B`, ans: `Bravo` },
  { que: `C`, ans: `Charlie` },
  { que: `D`, ans: `Delta` },
  { que: `E`, ans: `Echo` },
  { que: `F`, ans: `Foxtrot` },
  { que: `G`, ans: `Golf` },
  { que: `H`, ans: `Hotel` },
  { que: `I`, ans: `India` },
  { que: `J`, ans: `Juliett` },
  { que: `K`, ans: `Kilo` },
  { que: `L`, ans: `Lima` },
  { que: `M`, ans: `Mike` },
  { que: `N`, ans: `November` },
  { que: `O`, ans: `Oscar` },
  { que: `P`, ans: `Papa` },
  { que: `Q`, ans: `Quebec` },
  { que: `R`, ans: `Romeo` },
  { que: `S`, ans: `Sierra` },
  { que: `T`, ans: `Tango` },
  { que: `U`, ans: `Uniform` },
  { que: `V`, ans: `Victor` },
  { que: `W`, ans: `Whiskey` },
  { que: `X`, ans: `X-ray` },
  { que: `Y`, ans: `Yankee` },
  { que: `Z`, ans: `Zulu` },
];
